name: Deploy DotNet project to Azure Function App

on:
  [push]

env:
  FRIENDLY_NAME: azFunc-guidgen  
  SHORT_NAME: FuncGuidGen  
  LOCATION: 'eastus2'                
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'az login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        ls
        bash ./bash/setup.sh ${{ env.FRIENDLY_NAME }} ${{ env.SHORT_NAME }} ${{ env.LOCATION }}
        popd
